### ISSUE TITLE
ValueError: 150004 is not in list

### ISSUE THREAD

**Issue by littlerookie** [liangwq/Chatglm_lora_multi-gpu#11]
您好，参考之前的issue修改了skip_init问题之后，运行报错
![image](https://user-images.githubusercontent.com/8966194/229391456-be17a4d1-0350-4f62-b449-bc06f12e81cb.png)
请问有什么修改的建议吗

**Comment by liangwq** [comment]
> 您好，参考之前的issue修改了skip_init问题之后，运行报错 ![image](https://user-images.githubusercontent.com/8966194/229391456-be17a4d1-0350-4f62-b449-bc06f12e81cb.png) 请问有什么修改的建议吗

你完全复制我的项目部署吧
这个是emcode部分问题，代码修复过
EOS_ID = 150005

**Comment by liangwq** [comment]
> > 您好，参考之前的issue修改了skip_init问题之后，运行报错 ![image](https://user-images.githubusercontent.com/8966194/229391456-be17a4d1-0350-4f62-b449-bc06f12e81cb.png) 请问有什么修改的建议吗
> 
> 你完全复制我的项目部署吧 这个是emcode部分问题，代码修复过 EOS_ID = 150005

新增了token文件，你再拉下代码试试

**Comment by littlerookie** [comment]
> > > 您好，参考之前的issue修改了skip_init问题之后，运行报错 ![image](https://user-images.githubusercontent.com/8966194/229391456-be17a4d1-0350-4f62-b449-bc06f12e81cb.png) 请问有什么修改的建议吗
> > 
> > 
> > 你完全复制我的项目部署吧 这个是emcode部分问题，代码修复过 EOS_ID = 150005
> 
> 新增了token文件，你再拉下代码试试

好像没有报错了。另外我想再请教个问题，目前最低可以在多少显存的GPU上跑呢，除了修改per_device_train_batch_size，还有其他参数修改可以降低显存需求的吗？谢谢

**Comment by liangwq** [comment]
> > > > 您好，参考之前的issue修改了skip_init问题之后，运行报错 ![image](https://user-images.githubusercontent.com/8966194/229391456-be17a4d1-0350-4f62-b449-bc06f12e81cb.png) 请问有什么修改的建议吗
> > > 
> > > 
> > > 你完全复制我的项目部署吧 这个是emcode部分问题，代码修复过 EOS_ID = 150005
> > 
> > 
> > 新增了token文件，你再拉下代码试试
> 
> 好像没有报错了。另外我想再请教个问题，目前最低可以在多少显存的GPU上跑呢，除了修改per_device_train_batch_size，还有其他参数修改可以降低显存需求的吗？谢谢

1.bit减少
2.深度改deepspeed参数
3.用megatron
但其实如果真的工业应用，没有一定gpu还是不好搞的
你至多就是让模型能装进显存可以跑起来，后面要算的flop还是关键，跑不快不行的

**Comment by littlerookie** [comment]
好的，谢谢

**Comment by tutuxxx** [comment]
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/14323022/230726863-a4716766-bfb2-4a16-be87-1e9e08e6353a.png">
