### ISSUE TITLE
这个好像也有 训练完之后lora_B.weight全都是0 的问题

### ISSUE THREAD

**Issue by llplay** [liangwq/Chatglm_lora_multi-gpu#14]

**Comment by liangwq** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/9170648/229485173-b057cadf-3e99-4a4c-8da7-d2c2701b93ee.png)
这是我训完的结果，应该是你那参数设置不对了

**Comment by llplay** [comment]
@liangwq  你训练完chatglm-lora.pt 多大，我的怎么只有16K，感觉参数没有保存进去

**Comment by llplay** [comment]
@liangwq 好像只要offload改成cpu就会有这个问题  
offload_optimizer_device: cpu
offload_param_device: cpu

**Comment by liangwq** [comment]
> @liangwq 你训练完chatglm-lora.pt 多大，我的怎么只有16K，感觉参数没有保存进去

秩如果是8，差不多7M左右

**Comment by liangwq** [comment]
> @liangwq 好像只要offload改成cpu就会有这个问题
> offload_optimizer_device: cpu
> offload_param_device: cpu

你要这么改，要深入了解下deepspeed的zero3阶段参数设定
