### ISSUE TITLE
关于多GPU训练

### ISSUE THREAD

**Issue by z1968357787** [liangwq/Chatglm_lora_multi-gpu#24]
你好，我想请问一下，假如我有8张卡(0~7)，这个程序有没有办法能让我指定哪几张特定的卡运行（比如5~7）呢？

**Comment by liangwq** [comment]
> 你好，我想请问一下，假如我有8张卡(0~7)，这个程序有没有办法能让我指定哪几张特定的卡运行（比如5~7）呢？

可以的 执行前指定，用export CUDA_VISIBLE_DEVICES=0,1
