### ISSUE TITLE
title拼错了

### ISSUE THREAD

**Issue by huangxd-** [liangwq/Chatglm_lora_multi-gpu#26]
https://github.com/liangwq/Chatglm_lora_multi-gpu/blob/64636085e5c733f22b314ff632b157b5954a5960/chatglm_multi_gpu_inference.py#L23

**Comment by liangwq** [comment]
> https://github.com/liangwq/Chatglm_lora_multi-gpu/blob/64636085e5c733f22b314ff632b157b5954a5960/chatglm_multi_gpu_inference.py#L23

谢谢指正，已修改
