### ISSUE TITLE
一张卡能运行，两张卡报错

### ISSUE THREAD

**Issue by Flat-Chen** [liangwq/Chatglm_lora_multi-gpu#3]
3090*2
--nproc_per_node=2 改为1可以正常运行

![image](https://user-images.githubusercontent.com/56380091/228503437-e2480152-abf6-44ca-8b0c-54dee15010e1.png)

![image](https://user-images.githubusercontent.com/56380091/228503525-06a604c8-5e82-41d6-a3c3-1bceb199f13f.png)

没有找到更加详细的报错日志，小白冒昧问一下，低级问题麻烦大佬不要嘲笑

**Comment by Flat-Chen** [comment]
multi_gpu_fintune_belle.py代码运行到
model, optimizer, train_dataloader = accelerator.prepare(model, optimizer, train_dataloader)
开始报错

**Comment by liangwq** [comment]
> 
看报错事accelerate给的，你试试把accelerate升级，peft按require txt里面给的安装下

**Comment by Flat-Chen** [comment]
> > 
> 
> 看报错事accelerate给的，你试试把accelerate升级，peft按require txt里面给的安装下

**Comment by Flat-Chen** [comment]
感谢大佬，之前没有描述清楚是用docker环境运行
通过寻找accelerate的报错找到了一个issues：
https://github.com/huggingface/accelerate/issues/1254
docker run -it  --network host 解决
再次感谢大佬！


> > 
> 
> 看报错事accelerate给的，你试试把accelerate升级，peft按require txt里面给的安装下

**Comment by fancyerii** [comment]
> 感谢大佬，之前没有描述清楚是用docker环境运行 通过寻找accelerate的报错找到了一个issues： [huggingface/accelerate#1254](https://github.com/huggingface/accelerate/issues/1254) docker run -it --network host 解决 再次感谢大佬！
> 
> > > 
> > 
> > 
> > 看报错事accelerate给的，你试试把accelerate升级，peft按require txt里面给的安装下

我用docker run -it --network host好像也不行，你用了之后就好了吗？

**Comment by Flat-Chen** [comment]
--network host --ipc host

> > 感谢大佬，之前没有描述清楚是用docker环境运行 通过寻找accelerate的报错找到了一个issues： [huggingface/accelerate#1254](https://github.com/huggingface/accelerate/issues/1254) docker run -it --network host 解决 再次感谢大佬！
> > > > 
> > > 
> > > 
> > > 看报错事accelerate给的，你试试把accelerate升级，peft按require txt里面给的安装下
> 
> 我用docker run -it --network host好像也不行，你用了之后就好了吗？
