### ISSUE TITLE
多卡并行问题

### ISSUE THREAD

**Issue by awelldone** [liangwq/Chatglm_lora_multi-gpu#41]
博主你好 我用4张a100 40g进行多卡并行跑multi_gpu,py的时候 终端报NCCL错误，并且第一张卡显存爆了 
![1683982496509](https://github.com/liangwq/Chatglm_lora_multi-gpu/assets/128198109/9fa96ac5-2e01-45e4-a83e-edb5ef5868e5)
![1683982532168](https://github.com/liangwq/Chatglm_lora_multi-gpu/assets/128198109/ae34dc7e-308c-47b4-bce9-e7d72daaff41)
![1683982571409](https://github.com/liangwq/Chatglm_lora_multi-gpu/assets/128198109/c0c69a01-3658-4f70-b600-f856469b9b86)

**Comment by liangwq** [comment]
> 博主你好 我用4张a100 40g进行多卡并行跑multi_gpu,py的时候 终端报NCCL错误，并且第一张卡显存爆了 ![1683982496509](https://user-images.githubusercontent.com/128198109/238134609-9fa96ac5-2e01-45e4-a83e-edb5ef5868e5.png) ![1683982532168](https://user-images.githubusercontent.com/128198109/238134634-ae34dc7e-308c-47b4-bce9-e7d72daaff41.png) ![1683982571409](https://user-images.githubusercontent.com/128198109/238134662-c0c69a01-3658-4f70-b600-f856469b9b86.png)
把deepspeed的下面参数改小点，如果你的数据量可以，可以把lora的秩改大些
"gradient_accumulation_steps":2,
    "train_batch_size": 4,
