### ISSUE TITLE
多卡deepspeed模式

### ISSUE THREAD

**Issue by Tongjilibo** [liangwq/Chatglm_lora_multi-gpu#44]
想问下项目中deepspeed多卡是模型并行吗？就是把不同层拆分到不同的gpu上，这样我多张小显存的卡也能跑起来，是这样的吗？

**Comment by LLLyyy-777** [comment]
多卡应该是数据并行

**Comment by liangwq** [comment]
> 想问下项目中deepspeed多卡是模型并行吗？就是把不同层拆分到不同的gpu上，这样我多张小显存的卡也能跑起来，是这样的吗？

两种模式都提供了，模型拆到多张卡，同时支持批量预测
