### ISSUE TITLE
langchain版本是多少

### ISSUE THREAD

**Issue by jie1126** [liangwq/Chatglm_lora_multi-gpu#47]
ModuleNotFoundError: No module named 'langchain.callbacks.manager'
报了以上提示，langchain版本是多少，我安装的是0.0.401

**Comment by liangwq** [comment]
> ModuleNotFoundError: No module named 'langchain.callbacks.manager' 报了以上提示，langchain版本是多少，我安装的是0.0.401

langchain                     0.0.330
langchain-experimental        0.0.37
