### ISSUE TITLE
解析相应报错

### ISSUE THREAD

**Issue by jie1126** [liangwq/Chatglm_lora_multi-gpu#49]
![image](https://github.com/liangwq/Chatglm_lora_multi-gpu/assets/148535461/cecf2af4-ac6c-4ef5-a5f4-c2ef7c35ae23)
如上图，是不是没有检索出来？你的read.txt里面咋写的

**Comment by liangwq** [comment]
> ![image](https://user-images.githubusercontent.com/148535461/282397099-cecf2af4-ac6c-4ef5-a5f4-c2ef7c35ae23.png) 如上图，是不是没有检索出来？你的read.txt里面咋写的

看起来不是没检索出来，你看看chatglm3是不是支持stream_chat方法，不支持你可以选择非stram chat模式

**Comment by liangwq** [comment]
> > > ![image](https://user-images.githubusercontent.com/148535461/282397099-cecf2af4-ac6c-4ef5-a5f4-c2ef7c35ae23.png) 如上图，是不是没有检索出来？你的read.txt里面咋写的
> > 
> > 
> > 看起来不是没检索出来，你看看chatglm3是不是支持stream_chat方法，不支持你可以选择非stram chat模式
> 
> 支持的，就是响应有问题好像

read.txt:https://github.com/THUDM/ChatGLM2-6B/blob/main/README.md
