### ISSUE TITLE
偶现 ModuleNotFoundError: No module named 'transformers_modules.chatglm-6b.tokenization_chatglm'

### ISSUE THREAD

**Issue by llplay** [liangwq/Chatglm_lora_multi-gpu#5]
有时会出现
ModuleNotFoundError: No module named 'transformers_modules.chatglm-6b.tokenization_chatglm'
错误
不是100%复现

**Comment by liangwq** [comment]
换成chatglm-6b，不用autotoken加载试试

**Comment by llplay** [comment]
> autotoken
恩 改成直接用chatglm-6b的tokenizer就可以了

**Comment by llplay** [comment]
改成直接用chatglm-6b的tokenizer就可以了
